name: Update cpanfile.snapshot
on:
  schedule:
    - cron: "1 15 * * 0"
  workflow_dispatch:
jobs:
  update-dep:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Generate Auth Token
        id: auth-token
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - id: git-user
        name: Set up git user
        uses: haarg/setup-git-user@v1
        with:
          jwt: ${{ steps.auth-token.outputs.jwt }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.auth-token.outputs.access-token }}
      - name: Set up installation local::lib
        run: |
          mkdir -p $RUNNER_TEMP/perl5/bin
          mkdir -p $RUNNER_TEMP/perl5/lib/perl5
          echo "$RUNNER_TEMP/perl5/bin" >> "$GITHUB_PATH"
          echo "PERL5LIB=$RUNNER_TEMP/perl5/lib/perl5" >> "$GITHUB_ENV"
      - name: Get cpm
        run: |
          curl -sL -o $RUNNER_TEMP/perl5/bin/cpm https://raw.githubusercontent.com/skaji/cpm/main/cpm
          chmod +x $RUNNER_TEMP/perl5/bin/cpm
      - name: Install cpanm, Carton, and Carton::Snapshot
        run: >
          cpm install
          App::cpanminus
          Carton
          Carton::Snapshot
          --without-test
          --show-build-log-on-failure
          --local-lib-contained=$RUNNER_TEMP/perl5
      - name: Install forced deps
        run: >
          cpanm
          --cpanfile cpanfile.forced
          --showdeps --installdeps
          -L local
          -q
          .
          | cpm install
          --without-test
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib-contained=local
          --reinstall
          -
      - name: Install deps
        run: >
          cpm install
          --cpanfile cpanfile
          --resolver metacpan
          --show-build-log-on-failure
          --local-lib-contained=local
      - name: Maybe update cpanfile.snapshot
        run: carton
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.auth-token.outputs.access-token }}
          commit-message: Update cpanfile.snapshot
          title: Update cpanfile.snapshot
          author: ${{ steps.git-user.outputs.user-full }}
          committer: ${{ steps.git-user.outputs.user-full }}
          body: |
            [GitHub Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          branch: update-cpanfile-snapshot
